#
# Makefile for the DIOS extension to the Linux kernel.
#

KBUILD_EXTRA_SYMBOLS=/home/malte/Projects/dios/src/Module.symvers
#KBUILD_EXTMOD=/home/malte/Projects/dios/src

obj-y     := dios_syscalls.o utils.o

